version: "3.5"
services:
  localstack_sqs:
    container_name: sqs_consumer_starter_sqs
    image: localstack/localstack
    ports:
      - '4566-4599:4566-4599'
    command: sh -c "/usr/local/bin/init.sh && exec myexecutable"
    environment:
      - SERVICES=sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - DEBUG=0
    volumes:
      - "${HOST_TMP_FOLDER:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack_init:/etc/localstack/init/ready.d
    healthcheck:
      test: curl http://localhost:4566/_localstack/health | jq '.services.sqs' | grep -q -x 'running'
      interval: 20s
      retries: 5
      start_period: 20s
      timeout: 10s